### ISSUE TITLE
grid and axis

### ISSUE THREAD

**Issue by vinnitu** [danchitnis/webgl-plot#55]
I need grid (axis) on the graph for time series data.

Do you plan to add this feature?

**Comment by danchitnis** [comment]
See this example: https://codesandbox.io/s/webglplot-gird-b41j9?file=/src/index.ts

You can make more complicated examples, calculating the grid lines and displaying them. Inherently grids are just another set of lines. I may add some features in WebGL-Plot to facilitate this, but untimely it is up to the developer to make the grids.

**Comment by danchitnis** [comment]
Example provided here: 
https://danchitnis.github.io/webgl-plot-examples/vanilla/grid.html

**Comment by federicomassa** [comment]
What about displaying axis text, e.g. on the axes ticks? Thanks!
