### ISSUE TITLE
Unnecessary depth buffer?

### ISSUE THREAD

**Issue by boris-ulyanov** [danchitnis/webgl-plot#56]
I couldn't find where the depth buffer is used, if it's true, it's better to turn it off:
https://github.com/danchitnis/webgl-plot/blob/b445ae1ff729fa7f917b20036a8dd5085502e6ee/src/webglplot.ts#L146

or, if it is used, `||` (logical or) must be changed to `|` (bitwise or) in clear calls:
https://github.com/danchitnis/webgl-plot/blob/b445ae1ff729fa7f917b20036a8dd5085502e6ee/src/webglplot.ts#L149
https://github.com/danchitnis/webgl-plot/blob/b445ae1ff729fa7f917b20036a8dd5085502e6ee/src/webglplot.ts#L204

**Comment by danchitnis** [comment]
yes, depth is not being used (at least for now). I will investigate if switching it off affects anything in the library.

**Comment by danchitnis** [comment]
I have removed the depth buffer now, as it had now impact.
