### ISSUE TITLE
axis and text

### ISSUE THREAD

**Issue by danchitnis** [danchitnis/webgl-plot#61]
What about displaying axis text, e.g. on the axes ticks? Thanks!

_Originally posted by @federicomassa in https://github.com/danchitnis/webgl-plot/issues/55#issuecomment-831308574_

**Comment by danchitnis** [comment]
@federicomassa I have already implemented some aspect in [EEsim](https://eesim.dev). I have implemented the axis and text in canvas rather than webgl since it is easier to customize.

I will add an easy to understand example to the [webgl-plot examples](https://danchitnis.github.io/webgl-plot-examples/vanilla/) in the next week or two.

**Comment by federicomassa** [comment]
That'd be great! Thanks

**Comment by federicomassa** [comment]
Much appreciated, thanks!
