### ISSUE TITLE
The JSDeliver CDN doesn't work anymore?

### ISSUE THREAD

**Issue by polishdude20** [danchitnis/webgl-plot#62]
I'm not able to run the JSDeliver URL as a script anymore. Did that break?

**Comment by danchitnis** [comment]
@polishdude20 did you mean the umd examples? I have fixed these now since there was a change in the export naming of the module.

However, I strongly recommend using ES6 and Skypack if you are developing in the browser.

**Comment by polishdude20** [comment]
I mean using this code snippet:

`<script src="https://cdn.jsdelivr.net/gh/danchitnis/webgl-plot@master/dist/webglplot.umd.min.js"></script>`

It looks like the code returned from that page is the wrong one?

**Comment by danchitnis** [comment]
yes it works, see the examples:
[Codepen](https://codepen.io/danchitnis/pen/mdJVEYY)
[JSfiddle](https://jsfiddle.net/danchitnis/mfcw73z2/)
