### ISSUE TITLE
Docs: Add React code examples

### ISSUE THREAD

**Issue by disambiguator** [danchitnis/webgl-plot#71]
**Is your feature request related to a problem? Please describe.**
The React based examples on Vercel look great, but I'd love to see the actual React API for this.

**Describe the solution you'd like**
Can you link the React code powering the example?

**Describe alternatives you've considered**
I tried looking at the page source directly, but that's pretty obfuscated due to Webpack.

**Comment by disambiguator** [comment]
Ah, just found the code sandbox 🤦🏽 https://codesandbox.io/s/webgl-plot-react-8y1qj?fontsize=14&hidenavigation=1&theme=dark

**Comment by danchitnis** [comment]
@disambiguator The source code for the React examples is [here](https://github.com/danchitnis/webgl-plot-react). These are not APIs, just examples to get started.
