### ISSUE TITLE
xy Scatter plot

### ISSUE THREAD

**Issue by eniv** [danchitnis/webgl-plot#72]
Hi,
This library is great. It's been easy to use so far and lived up to any performance expectations I've had!
I was wondering if you considered adding an xy scatter plot and if you did and decided not to then why?
Thank you.

**Comment by danchitnis** [comment]
@eniv it was always in the plan, just didn't get time to do it. I have created [this example](https://danchitnis.github.io/webgl-plot-examples/vanilla/scatterXY.html) which uses `WebglSquare` to draw data points. This is not very efficient at the moment, and I have to modify the vertex shaders to get more performance. If you know very large scatter data sets which are public, then let me know so I can include them in the example.

**Comment by eniv** [comment]
That looks very promising. Thank you!
I don't have a specific large dataset to test this with in mind, but might be able to contribute one from my application once I can synthesize it.
